[[services]]
internal_port = 3000
protocol = "http"
name = "frontend"
project = "voiceapp2"

[services.environment]
NODE_ENV="production"

[[services]]
internal_port = 8080
protocol = "http"
name = "backend"
project = "voiceapp2"

[services.environment]
NODE_ENV="production"